# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Grameenphone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Grameenphone
  pod 'Alamofire', '~> 5.2'
  pod 'Kingfisher', '~> 5.0'
  pod 'CocoaLumberjack/Swift'
end
